### ISSUE TITLE
Installation fails - "cannot stat 'default.db': No such file or directory

### ISSUE THREAD

**Issue by tnorthcutt** [masukomi/hey#19]
When I try to install `hey`, this is the output after the db install step. This occurs whether I accept the suggestion to install to my Dropbox folder, or decline it.

```
cp: cannot stat 'default.db': No such file or directory
---------------------------------------------------------------
Your DB is installed at /Applications/hey.app/Contents/MacOS/database.db
If you choose to move it you will need to update the path in
~/.config/hey/config.json
Done. Happy tracking.
```

If I then proceed to try and execute `hey`, I get this output:

```
Error: (require) cannot load extension: srfi-19

	Call history:

	sql-de-lite.scm:934: condition-predicate
	sql-de-lite.scm:936: condition-property-accessor
	sql-de-lite.scm:937: condition-property-accessor
	hey.scm:17: ##sys#require
	hey.scm:18: ##sys#require
	numbers.scm:267: ##sys#gc
	numbers.scm:1770: register-feature!
	hey.scm:19: ##sys#require
	hey.scm:20: ##sys#require
	hey.scm:21: ##sys#require
	hey.scm:24: ##sys#require
	hey.scm:26: ##sys#require
	hey.scm:30: ##sys#require
	##sys#implicit-exit-handler
	hey.scm:31: ##sys#require
	hey-dates.scm:12: ##sys#require	  	<--
```

Happy to provide whatever other feedback is useful for debugging.

**Comment by blakedietz** [comment]
I'm seeing the same problem. I'm running this on High Sierra.

**Comment by tnorthcutt** [comment]
Relevant: https://twitter.com/masukomi/status/935934173004656640

> Thanks. I’d noticed, but unfortunately there’s a bug in the installer that I wasn’t ware of. :( and I’m in the middle of a rewrite that would make life easier for folks. … if only it could have waited 2 weeks.
